language: python
#This will run all the tests on python versions 3.6, 3.7, 3.8
#The default OS to run these is Linux.
#To use other OS see: https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
python:
  - "3.6"
  - "3.7"
  - "3.8"

# ensure pip is upgraded
before_install:
  - pip install pip --upgrade;
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
# command to run tests
script:
  - pytest
# don't want email results
notifications:
  email: false
# upload the codecov report
after_success:
  - bash <(curl -s https://codecov.io/bash)
